### ISSUE TITLE
Updating PDS error

### ISSUE THREAD

**Issue by picepice** [rosemalejohn/dnsc-hris#3]
ErrorException in 0b4700cdd9423cebe7c48b1c8477b026f9e27267.php line 180:
Undefined property: Illuminate\Database\Eloquent\Relations\HasMany::$id (View: C:\xampp\htdocs\dnsc-hris\resources\views\employee\create_partials\personal_informations.blade.php) (View: C:\xampp\htdocs\dnsc-hris\resources\views\employee\create_partials\personal_informations.blade.php)

this is what i encounter when updating pds..

another is when im adding children, looks like the calendar is only updating the first child (when you click the calendar, it only change the textbox of the first child)

**Comment by rosemalejohn** [comment]
Looks like you need to do some research, haha sorry I forgot how to do the fix with this. 

Try dumping the data on the controller or view for you to know, which causes the error. And also regarding with the calendar field, I cannot recall the it anymore but it seems because we clone the element with that maybe the event when you click a field is applied on the original field. Try to do some research with that. Thanks.

**Comment by picepice** [comment]
yes.. i really need to do alot of research.. Thanks anyway..
